import { Sparkles, X } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

export default function AISummaryModal({ open, onClose, summary }) {
  return (
    <AnimatePresence>
      {open && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-50 bg-black/40"
          aria-modal
          role="dialog"
        >
          <motion.div
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: 20, opacity: 0 }}
            transition={{ type: "spring", stiffness: 260, damping: 24 }}
            className="fixed inset-x-0 bottom-0 sm:inset-auto sm:top-1/2 sm:left-1/2 sm:-translate-x-1/2 sm:-translate-y-1/2 w-full sm:max-w-2xl bg-white rounded-t-2xl sm:rounded-2xl shadow-xl overflow-hidden"
          >
            <div className="p-4 border-b flex items-center justify-between">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-full bg-[#9c27b0]/10 flex items-center justify-center">
                  <Sparkles className="w-4 h-4 text-[#9c27b0]" />
                </div>
                <h3 className="font-semibold text-[#202124]">AI Summary</h3>
              </div>
              <button
                className="p-1 rounded hover:bg-gray-100"
                onClick={onClose}
                aria-label="Close"
              >
                <X className="w-5 h-5 text-gray-600" />
              </button>
            </div>

            <div className="p-4">
              <div className="rounded-lg border-2 border-[#9c27b0]/30 p-4 bg-[#9c27b0]/5">
                <p className="text-sm text-[#202124] leading-6">
                  {summary?.content || "This is a preview AI-generated summary of the selected lecture."}
                </p>
                <div className="mt-3 flex items-center justify-between text-xs text-[#5f6368]">
                  <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-white border border-[#9c27b0]/30 text-[#9c27b0]">
                    {summary?.word_count || 120} words
                  </span>
                  <span>Generated by {summary?.model_name || "mock-gpt"}</span>
                </div>
              </div>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
